name: Save Data Cron to dolar.db
permissions:
  contents: write
on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook

  schedule:
    - cron: "0 0  * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true
      - run: |
          npm run save
          git config user.name Dolar-api-bot
          git config user.email IamBot@bot.com 
          git add -A
          timestamp=$(date -u)
          git commit -h "lastest date update: $timestamp" || exit 0
          git push
